import { Toaster } from "sonner"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { ConvexProvider } from "@/components/providers/convex-provider";
import { ModalProvider } from "@/components/providers/modal-provider";
import { EdgeStoreProvider } from "@/lib/edgestore";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" suppressHydrationWarning>
          <body className={inter.className}>
              <ConvexProvider>
                  <EdgeStoreProvider>
                      <ThemeProvider
                          attribute="class"
                          defaultTheme="system"
                          enableSystem
                          disableTransitionOnChange
                          storageKey="user-theme"
                      >
                          <Toaster position="bottom-center" />
                          <ModalProvider />
                          {children}
                      </ThemeProvider>
                  </EdgeStoreProvider>
              </ConvexProvider>
          </body>
      </html>
  );
}
